FypWebsite/FypWebsite/urls.py
from django.contrib import admin
from django.urls import path
from userAuth.views import loginPage,logoutUser,register,homePage
from documentation.views import docsPage,createDoc,viewDoc,editDoc
from dynamicTables.views import tablesPage,createTable,viewTable
from notebooks.views import notebooksPage,viewNotebook,uploadNotebook
from pipelines.views import pipelinesPage,createPipeline,viewPipeline
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homePage),
    path('login/',loginPage),
    path('logout/',logoutUser),
    path('register/',register),
    path('pipelines/<str:pipe_slug>/',viewPipeline),
    path('pipelines/',pipelinesPage),
    path('create-pipeline/',createPipeline),
    path('tables/<str:view_slug>/',viewTable),
    path('tables/',tablesPage),
    path('create-table/',createTable),
    path('notebooks/<str:note_slug>/',viewNotebook),
    path('notebooks/',notebooksPage),
    path('upload-notebook/',uploadNotebook),
    path('docs/<str:edit_doc>/edit/',editDoc),
    path('docs/<str:view_doc>/',viewDoc),
    path('docs/',docsPage),
    path('create-doc/',createDoc),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FypWebsite/documentation/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
User =settings.AUTH_USER_MODEL
from django.template.defaultfilters import slugify

class DocumentationPost(models.Model):
    user = models.ForeignKey(User,default=1, on_delete=models.SET_DEFAULT)
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    def get_post_url(self):
        return f"/docs/{self.slug}"
    def get_edit_url(self):
        return f"/docs/{self.slug}/edit/"
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
class DocumentationImage(models.Model):
    def generate_image_path(self, filename):
        foldername = "media/%s/%s" % (self.post.slug.upper(), filename)
        return foldername
    post=models.ForeignKey(DocumentationPost,on_delete=models.CASCADE)
    image=models.ImageField(upload_to=generate_image_path)
    #print(image.url)
    image_number=models.IntegerField(default=1)
    caption=models.CharField(max_length=100)
    class Meta:
        unique_together = ('post', 'image_number')

@receiver(models.signals.post_delete, sender=DocumentationImage)
def auto_delete_image_on_delete(sender, instance, **kwargs):
    """
    Deletes notebook from filesystem
    when corresponding `image` object is deleted.
    """
    if instance.image:
        #print(instance.image.path)
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

FypWebsite/documentation/forms.py
from django import forms
from .models import DocumentationPost, DocumentationImage

class DocumentationPostForm(forms.ModelForm):
    class Meta:
        model = DocumentationPost
        fields = ['title','content','user']
    content=forms.CharField(widget=forms.Textarea(attrs={
        'style': 'width: 100%;resize: none;overflow: hidden;min-height: 50px;',
        'class':'form-control',
        'oninput':"auto_grow(this)"
    }))
    title=forms.CharField(widget=forms.TextInput(attrs={
        'style': 'width: 100%',
        'class':'form-control'
    }))
class DocumentationImageForm(forms.ModelForm):
    class Meta:
        model = DocumentationImage
        fields=['image','caption']

FypWebsite/documentation/views.py
from django.shortcuts import render,redirect
from .forms import DocumentationPostForm,DocumentationImageForm
from .models import DocumentationPost,DocumentationImage
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required

# Create your views here.
def docsPage(request):
    context={'active_view':'docs'}
    template_name="documentation/documentationlist.html"

    context['content_dicts']=[]
    doc_posts=DocumentationPost.objects.all()
    for post in doc_posts:
        context['content_dicts'].append({
            'title':post.title,
            'content':post.content,
            'url':post.get_post_url(),
            'user':post.user
            })

    context['content_template_name']="documentation/docListInner.html"

    return render(request,template_name,context)
@login_required(login_url="/login/")
def createDoc(request):
    context={'active_view':'docs'}
    template_name="documentation/createDoc.html"
    form=DocumentationPostForm()
    #print(request.POST)
    if request.method=="POST":
        form=DocumentationPostForm(data={'title':request.POST.get('title'),'content':request.POST.get('content'),'user':request.user})

        if form.is_valid():
            form.save()
            return redirect('/docs/'+slugify(request.POST.get('title'))+'/')
    context['form']=form
    return render(request,template_name,context)
@login_required(login_url="/login/")
def viewDoc(request,view_doc):
    context={'active_view':'docs'}
    template_name="documentation/viewDoc.html"
    doc=DocumentationPost.objects.filter(slug=view_doc)
    if doc.exists():
        doc_images=DocumentationImage.objects.filter(post=doc[0])
        context['post']={
        'title':doc[0].title,
        'content':doc[0].content,
        'user':doc[0].user,
        'edit':doc[0].get_edit_url(),
        'images':[{'url':im.image.url,'caption':im.caption} for im in doc_images]
        }
    return render(request,template_name,context)
@login_required(login_url="/login/")
def editDoc(request,edit_doc=""):
    context={'active_view':'documentation'}
    template_name="documentation/editDoc.html"

    doc_post=DocumentationPost.objects.filter(slug=edit_doc)
    if doc_post.exists():
        if request.user==doc_post[0].user:
            context['creator']=True
            form=DocumentationPostForm(data={'title':doc_post[0].title,'content':doc_post[0].content})
            imgs=DocumentationImage.objects.filter(post=doc_post[0])
            im_list=[]
            if imgs.exists():
                for im in imgs:
                    im_list.append(im.caption)
                context['images']=im_list
            print(request.POST)
            if request.method=="POST" and 'caption' in request.POST:
                success=False
                img_form=DocumentationImageForm(request.POST,request.FILES)
                if img_form.is_valid():
                    img=img_form.save(commit=False)
                    img.post=doc_post[0]
                    img.image_number=len(im_list)+1
                    img.save()
                    success=True
                    imgs=DocumentationImage.objects.filter(post=doc_post[0])
                    im_list=[]
                    if imgs.exists():
                        for im in imgs:
                            im_list.append(im.caption)
                        context['images']=im_list
            img_form=DocumentationImageForm()
            if request.method=="POST" and 'title' in request.POST:
                form=DocumentationPostForm(data={'title':request.POST.get('title'),'content':request.POST.get('content'),'user':request.user},instance=doc_post[0])
                if form.is_valid():
                    form.save()
                    return redirect('/docs/'+edit_doc+'/')
                    #print(form.cleaned_data.get('title'))
                    #doc_post[0].title=form.cleaned_data.get('title')
                    #doc_post[0].content=form.cleaned_data.get('content')
                    #doc_post[0].save()
            context['form']=form
            context['img_form']=img_form
    return render(request,template_name,context)

FypWebsite/documentation/templates/documentation/createDoc.html
{% extends "base.html" %}
{%block bodyblock%}
<div class="container-sm container-md form-control-group">
  <form method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <h1>Title: {{ form.title }}</h1>
    <div class="row justify-content-center">
      <h1>Content:</h1>
      <div class="col-6 text-center">
    {{form.content}}
      </div>
      <div class="col-6 markdown-preview bg-light text-wrap text-break">
      </div>

      <button class="btn btn-success w-25 my-2" type='submit'>Submit</button>


  </form>
</div>


{%endblock%}
{% block javascriptblock %}
  {% include 'markdown.html'%}
  <script>
    function auto_grow(element) {
    element.style.height = "5px";
    element.style.height = (element.scrollHeight)+"px";
    };

    var content;
    $('#id_content').on('change keyup paste', function() {
    content=$(this).val();
    $(".markdown-preview").html(marked(content));
    MathJax.typeset()
    });
  </script>
{% endblock %}

FypWebsite/documentation/templates/documentation/docListInner.html
{% extends "card_inner.html" %}
{% block title %}
  {{fed_data.title}}
{% endblock %}
{% block main_body %}
<hr/>
<div class="markdown-content small">
{{fed_data.content|truncatechars:200}}
</div>
<hr/>
{% endblock %}
{% block second_body %}
  <h6>Created By</h6>
  {{fed_data.user}}
{% endblock %}
{% block footer %}
  <button onclick="location.href='{{fed_data.url}}'" type="button" class="btn btn-success">
    View Post</button>
{% endblock %}

FypWebsite/documentation/templates/documentation/documentationlist.html
{% extends "base.html" %}
{%block bodyblock%}
<div class="px-2 text-center">
<button onclick="location.href='/create-doc/'" type="button" class="btn btn-primary">
  Create Doc</button>
</div>
<div class="row justify-content-center">
  {%for obj in content_dicts%}
    {% include 'card_container.html' with content_dict=obj content_template_name=content_template_name%}
  {% endfor %}
</div>
{%endblock%}
{% block javascriptblock %}
  {% load static %}
  {% include 'markdown.html'%}
  <script>
    $(document).ready(function(){
      var content,marked_content
      $(".markdown-content").each(function(){
      content=$(this).text();
      console.log(content)
      marked_content=marked(content);
      $(this).html(marked_content);
    });
    });
</script>
{% endblock %}

FypWebsite/documentation/templates/documentation/editDoc.html
{% extends "base.html" %}
{%block bodyblock%}

{% if creator%}
<div class="container-sm container-md form-control-group">
    <div class="row justify-content-center">
      <div class="col-6">
    <h1>Images:</h1></div><div class="col-6"><h1>Uploaded:</h1></div></div>
    <div class="row justify-content-center">
      <div class="col-6">
    <form method="POST"  enctype="multipart/form-data" id="imageForm">
      {% csrf_token %}
     {{ img_form.image }}
     <h5 class="my-2">Caption: {{img_form.caption}}</h5>
      <input type="submit" class="btn btn-success w-25 py-1" id="imageFormButton" value="Add">
    </form>
     </div>
     <div class="col-6 text-center">
     <ul class="list-group list-group-horizontal">
     {%for im in images %}
     <li class="list-group-item">{{im}}</li>
    {%endfor%}
    </ul>
    </div>
    </div>
    <form method='POST' enctype='multipart/form-data'>
      {% csrf_token %}
      <h1>Title: {{ form.title }}</h1>
    <div class="row justify-content-center">
      <h1>Content:</h1>
      <div class="col-6 text-center">
    {{form.content}}
      </div>
      <div class="col-6 markdown-preview bg-light text-wrap text-break">
      </div>
      <button class="btn btn-success w-25 my-2" type='submit'>Submit</button>
  </form>
</div>
{% else %}
Only the creater of this post can edit it.
{% endif %}

{%endblock%}
{% block javascriptblock %}
{% if creator %}
{% load static %}
{% include 'markdown.html'%}
<script>
function auto_grow(element) {
element.style.height = "5px";
element.style.height = (element.scrollHeight)+"px";
};
auto_grow($("#id_content")[0]);
</script>
<script>
  $(".markdown-preview").html(marked($('#id_content').text()));

  var content;
  $('#id_content').on('change keyup paste', function() {
  content=$(this).val();
  $(".markdown-preview").html(marked(content));
  MathJax.typeset()
  });
</script>
{% endif %}
{% endblock %}

FypWebsite/documentation/templates/documentation/viewDoc.html
{% extends "base.html" %}
{%block bodyblock%}
<div class="container-sm container-md">
<h1 class="border-bottom">{{post.title}} {% if request.user.is_authenticated %}
<button onclick="location.href='{{post.edit}}'" type="button" class="my-1 btn btn-success">
Edit</button>
{%endif%}</h1>
<div class="sm markdown-content bg-light text-wrap text-break">
{{post.content}}
</div>

<div class="row justify-content-center">
{%for im in post.images%}
<div class="col-sm-12 col-md-6 col-lg-4 col-xlg-3 my-4">
  <div class="card px-1 mx-auto bg-light text-center">
<img src='{{im.url}}' class="img-responsive" style="display: block;max-width:100%;max-height:500px;width: auto;height: auto;">
{{im.caption}}
  </div>
</div>
{%endfor%}
</div>
</br>

Created by: {{post.user}}
{% if request.user.is_authenticated %}
<button onclick="location.href='{{post.edit}}'" type="button" class="btn btn-success">
Edit</button>
{%endif%}
</div>
{%endblock%}
{% block javascriptblock %}
  {% load static %}
  {% include 'markdown.html'%}
  <script>
    $(document).ready(function(){
      var content,marked_content
      $(".markdown-content").each(function(){
      content=$(this).text();
      console.log(content)
      marked_content=marked(content);
      $(this).html(marked_content);
    });
    });
</script>
{% endblock %}